<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="AMIT" failures="5" tests="5" name="BankingApp Test(failed)(failed)(failed)(failed)(failed)" time="48.38" errors="0" timestamp="2022-06-12T12:43:25 IST">
  <testcase classname="com.inetBankingV1.TestCases.TC_AddCustomerTest_003" name="addNewCustomer" time="15.73">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBankingV1.TestCases.TC_AddCustomerTest_003.addNewCustomer(TC_AddCustomerTest_003.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at runner.TestRunner.main(TestRunner.java:25)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- addNewCustomer -->
  <testcase classname="com.inetBankingV1.TestCases.TC_loginDDT_002" name="loginDDT" time="5.18">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBankingV1.TestCases.TC_loginDDT_002.loginDDT(TC_loginDDT_002.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at runner.TestRunner.main(TestRunner.java:25)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.inetBankingV1.TestCases.TC_loginDDT_002" name="loginDDT" time="5.414">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBankingV1.TestCases.TC_loginDDT_002.loginDDT(TC_loginDDT_002.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at runner.TestRunner.main(TestRunner.java:25)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.inetBankingV1.TestCases.TC_loginDDT_002" name="loginDDT" time="4.834">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBankingV1.TestCases.TC_loginDDT_002.loginDDT(TC_loginDDT_002.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at runner.TestRunner.main(TestRunner.java:25)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.inetBankingV1.TestCases.TC_loginDDT_002" name="loginDDT" time="5.375">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBankingV1.TestCases.TC_loginDDT_002.loginDDT(TC_loginDDT_002.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at runner.TestRunner.main(TestRunner.java:25)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
</testsuite> <!-- BankingApp Test(failed)(failed)(failed)(failed)(failed) -->
